name: only_results
description: A dart implementation of Rusts Result type
version: 1.0.0
repository: https://github.com/MyLittlePenguin/only_results

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
